### ISSUE TITLE
nPower bug

### ISSUE THREAD

**Issue by thunderchylde** [Grimsbain/NeavUI-Grimsbain#1]
4x nPower\core.lua:16: Attempt to register unknown event "UNIT_COMBO_POINTS"
[C]: in function `RegisterUnitEvent'
nPower\core.lua:16: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "UNIT_COMBO_POINTS"
(*temporary) = "player"

**Comment by Grimsbain** [comment]
My version of NeavUI doesn't include nPower so I haven't looked into updating it.
