### ISSUE TITLE
nMainbar - Pet bar texture

### ISSUE THREAD

**Issue by Technojo01** [Grimsbain/NeavUI-Grimsbain#2]
When not using any bottom bars, you can see the (new?) pet texture bar from blizzard: [nMainbar](https://i.imgur.com/fxkFoB4.png)

Without it: [Blizzard](https://i.imgur.com/a0c5B96.png)

No big deal though!

**Comment by Grimsbain** [comment]
Thanks for the report. Didn't know that was a thing. Fixed in 82b24a5de7a01322055291554b9c4c21dff6c4bc.
