### ISSUE TITLE
oUF Neav - Level

### ISSUE THREAD

**Issue by Technojo01** [Grimsbain/NeavUI-Grimsbain#4]
Hey, just dinged and the level didn't properly showed in the player unit frame. Not sure if this is an oUF issue or not.

[Image](https://i.imgur.com/xcV6yFq.png)

**Comment by Grimsbain** [comment]
Fixed in 3ceca1b638e692d5a390f36361e1d69b8e0a8b05. I had the level element hidden during combat and reset so events didn't trigger properly.
