### ISSUE TITLE
ShareMedia 3.0

### ISSUE THREAD

**Issue by Technojo01** [Grimsbain/NeavUI-Grimsbain#4]
Hello again, thanks for fixing the quest tracker. I'm getting this now about share media. Should I just get it?

> Message: Interface\AddOns\nMedia\fonts.lua:2: Cannot find a library instance of "LibSharedMedia-3.0".
Time: Wed Jul 18 18:29:10 2018
Count: 1
Stack: Interface\AddOns\nMedia\fonts.lua:2: Cannot find a library instance of "LibSharedMedia-3.0".
[C]: in function `error'
Interface\AddOns\nMainbar\Libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\nMedia\fonts.lua:2: in main chunk
Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

**Comment by Grimsbain** [comment]
Woops should add a check for that. If you don't have an addon that uses LibSharedMedia you can disable or delete that addon. I used it for adding sounds to WeakAuras and BigWigs.

**Comment by Grimsbain** [comment]
Should be fixed now. I also added a fix for the nTooltip backdrop flashing.
